### PR TITLE
Set config

### PR DESCRIPTION
**Pull request by GyanP**
required for https://github.com/superdesk/superdesk-client-core/pull/3375

### CODE REVIEW

**Review by petrjasek — APPROVED** [review]

**Comment by petrjasek** [comment]
we shouldn't use develop here, so either that feature must go into 1.33 or it must wait

**Comment by petrjasek** [comment]
what about creating develop branch here and use it there?

**Comment by GyanP** [comment]
> what about creating develop branch here and use it there?

I think it's a good idea to have it. Most of the time when I do something for the client repo, and if the versions are different I create a dummy PR just for testing purposes and assign the ticket to QA to test it on that PR instance. And eventually, we never test it in the master instance of the client repo

**Comment by petrjasek** [comment]
ok, I've created the branch, you can make the PR there

**Comment by petrjasek** [comment]
my bad, I can change base here, both branches are same now

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
